using TiHiY.SystemOptimizer.Core;
using TiHiY.SystemOptimizer.Models;
namespace TiHiY.SystemOptimizer.UI;
public sealed class MainForm:Form
{
    private readonly SystemScanner scanner=new(); private readonly RecommendationEngine engine=new(); private readonly BackupService backup=new(); private readonly OptimizationService optimizer=new();
    private readonly FlowLayoutPanel cards=new(); private readonly Label status=new(),score=new(); private readonly Button apply=new(); private IReadOnlyList<OptimizationItem> items=Array.Empty<OptimizationItem>();
    public MainForm(){ Text="TiHiY System Optimizer"; Width=1180; Height=760; MinimumSize=new Size(1000,680); StartPosition=FormStartPosition.CenterScreen; BackColor=Theme.Background; ForeColor=Theme.Text; Font=new Font("Segoe UI",10f); BuildUi(); Shown+=async(_,_)=>await ScanAsync(); }
    private void BuildUi(){ var sidebar=new Panel{Dock=DockStyle.Left,Width=245,BackColor=Theme.Sidebar,Padding=new Padding(24)}; sidebar.Controls.Add(new Label{Text="⚡  TiHiY",AutoSize=true,Font=new Font("Segoe UI Semibold",23f),ForeColor=Theme.Text,Location=new Point(24,28)}); sidebar.Controls.Add(new Label{Text="SYSTEM OPTIMIZER",AutoSize=true,Font=new Font("Segoe UI",8.5f),ForeColor=Theme.Accent,Location=new Point(63,70)}); var y=128; foreach(var text in new[]{"⌂   Головна","◉   Комп'ютер","▣   Windows","◆   Ігри","★   Star Citizen","↶   Відновлення"}){ var b=new Button{Text=text,FlatStyle=FlatStyle.Flat,Width=197,Height=48,Location=new Point(24,y),TextAlign=ContentAlignment.MiddleLeft,Padding=new Padding(14,0,0,0),ForeColor=text.Contains("Головна")?Theme.Accent:Theme.Muted,BackColor=text.Contains("Головна")?Theme.Card:Theme.Sidebar}; b.FlatAppearance.BorderSize=0; sidebar.Controls.Add(b); y+=56; } Controls.Add(sidebar);
        var content=new Panel{Dock=DockStyle.Fill,Padding=new Padding(34,28,34,24),BackColor=Theme.Background}; content.Controls.Add(new Label{Text="Стан вашого ПК",AutoSize=true,Font=new Font("Segoe UI Semibold",25f),ForeColor=Theme.Text,Location=new Point(34,26)}); status.Text="Збираємо інформацію…"; status.AutoSize=true; status.ForeColor=Theme.Muted; status.Font=new Font("Segoe UI",11f); status.Location=new Point(37,72); content.Controls.Add(status);
        var summary=new RoundedPanel{BackColor=Theme.Card,Radius=22,Location=new Point(34,112),Size=new Size(835,142),Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right}; score.Text="—"; score.Font=new Font("Segoe UI Semibold",42f); score.ForeColor=Theme.Accent; score.AutoSize=true; score.Location=new Point(28,26); summary.Controls.Add(score); summary.Controls.Add(new Label{Text="ОЦІНКА СИСТЕМИ",Font=new Font("Segoe UI",9f),ForeColor=Theme.Muted,AutoSize=true,Location=new Point(31,93)}); apply.Text="Оптимізувати вибране"; apply.Size=new Size(230,52); apply.Anchor=AnchorStyles.Top|AnchorStyles.Right; apply.Location=new Point(summary.Width-258,44); apply.FlatStyle=FlatStyle.Flat; apply.FlatAppearance.BorderSize=0; apply.BackColor=Theme.Accent2; apply.ForeColor=Color.White; apply.Font=new Font("Segoe UI Semibold",11f); apply.Enabled=false; apply.Click+=async(_,_)=>await ApplyAsync(); summary.Controls.Add(apply); summary.Resize+=(_,_)=>apply.Location=new Point(summary.Width-258,44); content.Controls.Add(summary);
        content.Controls.Add(new Label{Text="Рекомендації",Font=new Font("Segoe UI Semibold",17f),ForeColor=Theme.Text,AutoSize=true,Location=new Point(34,278)}); cards.Location=new Point(34,320); cards.Size=new Size(835,360); cards.Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right; cards.AutoScroll=true; cards.FlowDirection=FlowDirection.TopDown; cards.WrapContents=false; cards.BackColor=Theme.Background; content.Controls.Add(cards); Controls.Add(content); }
    private async Task ScanAsync(){ try{ apply.Enabled=false; cards.Controls.Clear(); status.Text="Аналізуємо Windows та обладнання…"; var snap=await scanner.ScanAsync(); items=engine.Analyze(snap); var good=items.Count(x=>x.Level==RecommendationLevel.Good); score.Text=$"{78+(int)Math.Round(22d*good/Math.Max(1,items.Count))}/100"; status.Text=$"{snap.Cpu}  •  {snap.Gpu}  •  {snap.Ram}"; foreach(var item in items) cards.Controls.Add(CreateCard(item)); apply.Enabled=items.Any(x=>x.Selected); } catch(Exception ex){ MessageBox.Show(ex.Message,"Помилка аналізу",MessageBoxButtons.OK,MessageBoxIcon.Error); } }
    private Control CreateCard(OptimizationItem item){ var card=new RoundedPanel{Width=Math.Max(740,cards.ClientSize.Width-25),Height=104,BackColor=Theme.Card,Margin=new Padding(0,0,0,12),Radius=16}; var check=new CheckBox{Checked=item.Selected,AutoSize=true,Location=new Point(20,42)}; check.CheckedChanged+=(_,_)=>{item.Selected=check.Checked;apply.Enabled=items.Any(x=>x.Selected);}; card.Controls.Add(check); card.Controls.Add(new Label{Text=item.Title,AutoSize=true,Font=new Font("Segoe UI Semibold",12f),ForeColor=Theme.Text,Location=new Point(55,17)}); card.Controls.Add(new Label{Text=item.Summary,AutoSize=true,Font=new Font("Segoe UI",9.5f),ForeColor=Theme.Muted,Location=new Point(56,49)}); card.Controls.Add(new Label{Text=$"{item.CurrentValue}  →  {item.RecommendedValue}",AutoSize=true,Font=new Font("Segoe UI Semibold",9f),ForeColor=item.Level==RecommendationLevel.Good?Theme.Good:Theme.Warning,Location=new Point(56,74)}); var details=new Button{Text="Докладніше",FlatStyle=FlatStyle.Flat,Width=105,Height=32,Location=new Point(card.Width-125,36),Anchor=AnchorStyles.Top|AnchorStyles.Right,BackColor=Theme.CardHover,ForeColor=Theme.Text}; details.FlatAppearance.BorderSize=0; details.Click+=(_,_)=>MessageBox.Show(item.Details,item.Title); card.Controls.Add(details); return card; }
    private async Task ApplyAsync(){ var selected=items.Where(x=>x.Selected).ToArray(); if(selected.Length==0)return; if(MessageBox.Show($"Буде застосовано змін: {selected.Length}.\nПеред змінами буде створена резервна копія. Продовжити?","Підтвердження",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return; apply.Enabled=false; try{ var folder=backup.CreateBackup(selected.Select(x=>x.Id)); var log=await optimizer.ApplyAsync(selected,new Progress<string>(s=>status.Text=$"Застосовуємо: {s}…")); await File.WriteAllLinesAsync(Path.Combine(folder,"apply.log"),log); var failed=log.Count(x=>x.StartsWith("ПОМИЛКА")); MessageBox.Show($"Готово.\nРезервна копія: {folder}"+(selected.Any(x=>x.RequiresRestart)?"\nДля завершення перезавантажте ПК.":""),"TiHiY System Optimizer",MessageBoxButtons.OK,failed==0?MessageBoxIcon.Information:MessageBoxIcon.Warning); await ScanAsync(); } catch(Exception ex){ MessageBox.Show(ex.Message,"Помилка",MessageBoxButtons.OK,MessageBoxIcon.Error); } finally{apply.Enabled=true;} }
}
