using Microsoft.Win32;
using System.Text.Json;
using System.Text.RegularExpressions;
using TiHiY.SystemOptimizer.Models;

namespace TiHiY.SystemOptimizer.Core;

public sealed class BackupService
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };

    public string CreateBackup(IEnumerable<string> ids)
    {
        var items = ids.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
        var root = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),
            "TiHiY",
            "SystemOptimizer",
            "Backups",
            DateTime.Now.ToString("yyyyMMdd-HHmmss"));

        Directory.CreateDirectory(root);

        var state = new BackupState
        {
            CreatedAt = DateTime.Now,
            Items = items,
            PowerSchemeGuid = items.Contains("power-plan", StringComparer.OrdinalIgnoreCase)
                ? ReadActivePowerSchemeGuid()
                : null
        };

        if (items.Contains("game-mode", StringComparer.OrdinalIgnoreCase))
        {
            state.RegistryValues.Add(ReadRegistryValue(RegistryHive.CurrentUser, @"SOFTWARE\Microsoft\GameBar", "AutoGameModeEnabled"));
        }

        if (items.Contains("game-dvr", StringComparer.OrdinalIgnoreCase))
        {
            state.RegistryValues.Add(ReadRegistryValue(RegistryHive.CurrentUser, @"System\GameConfigStore", "GameDVR_Enabled"));
        }

        if (items.Contains("hags", StringComparer.OrdinalIgnoreCase))
        {
            state.RegistryValues.Add(ReadRegistryValue(RegistryHive.LocalMachine, @"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HwSchMode"));
        }

        if (items.Contains("mouse-accel", StringComparer.OrdinalIgnoreCase))
        {
            state.RegistryValues.Add(ReadRegistryValue(RegistryHive.CurrentUser, @"Control Panel\Mouse", "MouseSpeed"));
            state.RegistryValues.Add(ReadRegistryValue(RegistryHive.CurrentUser, @"Control Panel\Mouse", "MouseThreshold1"));
            state.RegistryValues.Add(ReadRegistryValue(RegistryHive.CurrentUser, @"Control Panel\Mouse", "MouseThreshold2"));
        }

        File.WriteAllText(Path.Combine(root, "state.json"), JsonSerializer.Serialize(state, JsonOptions));
        File.WriteAllText(
            Path.Combine(root, "manifest.json"),
            JsonSerializer.Serialize(new
            {
                createdAt = state.CreatedAt,
                items,
                note = "Star Citizen shader cache is regenerated by the game and is intentionally not backed up."
            }, JsonOptions));

        Export(root, "HKCU", @"Software\Microsoft\GameBar", "gamebar.reg");
        Export(root, "HKCU", @"System\GameConfigStore", "gameconfig.reg");
        Export(root, "HKCU", @"Control Panel\Mouse", "mouse.reg");
        Export(root, "HKLM", @"SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "graphics.reg");
        File.WriteAllText(
            Path.Combine(root, "power-plan.txt"),
            CommandRunner.RunAsync("powercfg", "/getactivescheme").GetAwaiter().GetResult().Output);

        return root;
    }

    public string? GetLatestBackupFolder()
    {
        var root = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),
            "TiHiY",
            "SystemOptimizer",
            "Backups");

        if (!Directory.Exists(root))
        {
            return null;
        }

        return Directory.GetDirectories(root)
            .Where(path => File.Exists(Path.Combine(path, "state.json")))
            .OrderByDescending(path => path, StringComparer.OrdinalIgnoreCase)
            .FirstOrDefault();
    }

    private static RegistryValueState ReadRegistryValue(RegistryHive hive, string path, string name)
    {
        try
        {
            using var baseKey = RegistryKey.OpenBaseKey(hive, RegistryView.Registry64);
            using var key = baseKey.OpenSubKey(path);
            if (key is null)
            {
                return NewMissing(hive, path, name);
            }

            var names = key.GetValueNames();
            var existed = names.Contains(name, StringComparer.OrdinalIgnoreCase);
            if (!existed)
            {
                return NewMissing(hive, path, name);
            }

            var value = key.GetValue(name, null, RegistryValueOptions.DoNotExpandEnvironmentNames);
            var kind = key.GetValueKind(name);
            return new RegistryValueState
            {
                Hive = hive.ToString(),
                Path = path,
                Name = name,
                Existed = true,
                Kind = kind.ToString(),
                Value = Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture)
            };
        }
        catch
        {
            return NewMissing(hive, path, name);
        }
    }

    private static RegistryValueState NewMissing(RegistryHive hive, string path, string name)
    {
        return new RegistryValueState
        {
            Hive = hive.ToString(),
            Path = path,
            Name = name,
            Existed = false,
            Kind = string.Empty,
            Value = null
        };
    }

    private static string? ReadActivePowerSchemeGuid()
    {
        try
        {
            var output = CommandRunner.RunAsync("powercfg", "/getactivescheme").GetAwaiter().GetResult().Output;
            var match = Regex.Match(output, @"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}");
            return match.Success ? match.Value : null;
        }
        catch
        {
            return null;
        }
    }

    private static void Export(string root, string hive, string path, string file)
    {
        try
        {
            CommandRunner.RunAsync("reg.exe", $"export \"{hive}\\{path}\" \"{Path.Combine(root, file)}\" /y")
                .GetAwaiter()
                .GetResult();
        }
        catch
        {
            // Exact per-value state in state.json is the primary rollback mechanism.
        }
    }
}
